name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      #- name: Run tests
      #  run: npm test

      # Notify ClickUp Chat - Success
      - name: Notify ClickUp Chat - Success
        if: success()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.CLICKUP_API_TOKEN }}" \
          -d '{
                "type": "message",
                "content": "✅ CI Passed for commit $GITHUB_SHA on branch ${{ GITHUB_REF }}. See run: ${{ GITHUB_SERVER_URL }}/${{ $GITHUB_REPOSITORY }}/actions/runs/${{ GITHUB_RUN_ID }}",
                "notify_all": true
              }' \
          "https://api.clickup.com/api/v3/workspaces/${{ secrets.CLICKUP_TEAM_ID }}/chat/channels/${{ secrets.CLICKUP_ROOM_ID }}/messages" 
          
          
      # Notify ClickUp Chat - Failure
      - name: Notify ClickUp Chat - Failure
        if: failure()
        run: |
          curl -X POST \
          -H "Authorization: ${{ secrets.CLICKUP_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "type": "message",
                "content": "❌ CI Failed for commit $GITHUB_SHA on branch $GITHUB_REF. See run: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
                "notify_all": true
              }' \
          "https://api.clickup.com/api/v3/workspaces/${{ secrets.CLICKUP_TEAM_ID }}/chat/channels/${{ secrets.CLICKUP_ROOM_ID }}/messages" 
