name: Deploy to Cloud Run (DEV)

on:
  push:
    branches:
      - uat

jobs:
  deploy-uat:
    uses: ./.github/actions/gcp-build-and-deploy.yml@${{ github.ref_name }}
    with:
      environment: uat